# Generated by Django 5.1.6 on 2025-03-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_user_delete_usersdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
