# Generated by Django 5.1.6 on 2025-03-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
