# Generated by Django 5.1.6 on 2025-04-06 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_to',
        ),
        migrations.AddField(
            model_name='task',
            name='created_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks_to_do', to=settings.AUTH_USER_MODEL),
        ),
    ]
