# Generated by Django 5.1.6 on 2025-04-06 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsapp', '0002_remove_task_created_to_task_created_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_to',
            field=models.ManyToManyField(blank=True, related_name='tasks_to_do', to=settings.AUTH_USER_MODEL),
        ),
    ]
