# Generated by Django 5.1.6 on 2025-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsapp', '0005_board_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
