# Generated by Django 5.1.6 on 2025-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsapp', '0006_alter_task_created_date_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('overdue', 'Просрочено')], default='В процессе', max_length=20, verbose_name='Статус'),
        ),
    ]
