# Generated by Django 5.1.7 on 2025-05-04 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardsapp', '0009_alter_comment_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_to',
            field=models.ManyToManyField(blank=True, related_name='tasks_to_do', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные за задачу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Выполнено', 'Выполнено'), ('В Ожидании проверки', 'В Ожидании проверки'), ('Просрочено', 'Просрочено')], default='В процессе', max_length=20, verbose_name='Статус'),
        ),
    ]
